name: Run Python Script

on:
  schedule:
    - cron: '40 5 * * *'
  workflow_dispatch:
        
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # If you have any dependencies

      - name: Run Geeksforgeeks Python script
        run: python ./script/gfg.py

      - name: Run leetcode Python script
        run: python ./script/leetcode.py

      - name: check readme content
        run: cat README.md
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with badges data"
          git push
